# Generated by Django 4.2.7 on 2023-12-05 14:08

import ScanCraft.apps.core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=255, unique=True)),
                ('file_input', models.FileField(upload_to=ScanCraft.apps.core.models.rename_uploaded_file)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_is_processing', models.BooleanField(default=False)),
                ('status_is_processed', models.BooleanField(default=False)),
                ('callback_token_update', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
